name: Pull Request Worflow
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Compile and build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npm run build
